export const AllLabels = {
	mutualFund: 'Mutual Funds',
	ppf: 'Public Provident Fund',
	nps: 'National Pension Scheme',
	rd: 'Recurring Deposits',
	fd: 'Fixed Deposits',
	frsb: 'Floating Rate Savings Bond',
	tBills: 'Treasury Bills',
	sgb: 'Sovereign Gold Bond',
	goldEtf: 'Gold ETFs',
	shoonyaEtf: 'Shoonya ETFs',
	canaraMf: 'Canara Robecco Mutual Fund',
	canaraElssMf: 'Canara Robecco ELSS Tax Saver Fund',
	hdfcMf: 'HDFC Mutual Fund',
	hdfcGoldMf: 'HDFC Gold Fund',
	hdfcNiftyMf: 'HDFC Index Fund - NIFTY 50 Plan',
	hdfcSensexMf: 'HDFC Index Fund - S&P BSE SENSEX Plan',
	iciciMf: 'ICICI Prudential Mutual Fund',
	iciciRetirementMf: 'ICICI Prudential Retirement Fund Pure Equity Plan',
	nipponMf: 'Nippon India Mutual Fund',
	nipponGoldMf: 'Nippon India Gold Savings Fund',
	nipponSmallMf: 'Nippon India Small Cap Fund',
	paragMf: 'PPFAS Mutual Fund',
	paragFlexiMf: 'Parag Parikh Flexi Cap Fund',
	sbiMf: 'SBI Mutual Fund',
	sbiGoldMf: 'SBI Gold Fund',
	sbiLargeMidMf: 'SBI Large & Midcap Fund',
	sbiSmallMf: 'SBI Small Cap Fund',
	tataMf: 'Tata Mutual Fund',
	tataLargeMidRegMF: 'Tata Large & Mid Cap Fund - Regular',
	tataSmallRegMF: 'Tata Small Cap Fund - Regular',
	tataGoldMf: 'Tata Gold ETF Fund of Fund',
	tataSmallMf: 'Tata Small Cap Fund',
	utiMf: 'UTI Mutual Fund',
	utiGoldMf: 'UTI Gold ETF Fund of Fund',
	utiNiftyMf: 'UTI Nifty 50 Index Fund',
	utiSensexMf: 'UTI S&P BSE Sensex Index Fund',
};
